name: a2m
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.9.24
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1q
  - pillow=9.2.0
  - pip=22.2.2
  - python=3.7.13
  - pytorch=1.6.0
  - readline=8.1.2
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.3
  - tk=8.6.12
  - torchvision=0.7.0
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - astunparse==1.6.3
    - blis==0.7.9
    - cachetools==5.2.0
    - catalogue==2.0.8
    - charset-normalizer==2.1.1
    - click==8.1.3
    - confection==0.0.3
    - cycler==0.11.0
    - cymem==2.0.7
    - ffmpeg==1.4
    - flatbuffers==22.9.24
    - fonttools==4.37.4
    - gast==0.4.0
    - google-auth==2.13.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.49.1
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - jinja2==3.1.2
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - langcodes==3.3.0
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.5.3
    - murmurhash==1.0.9
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==21.3
    - pathy==0.6.2
    - preshed==3.0.8
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.9.2
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.7.3
    - smart-open==5.2.1
    - spacy==3.4.1
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.0.1
    - thinc==8.1.4
    - tqdm==4.64.1
    - typer==0.4.2
    - typing-extensions==4.1.1
    - urllib3==1.26.12
    - wasabi==0.10.1
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.9.0
